version: "3.9"
volumes:
    svnData:
    svnConfig:
    svnadminConfig:
services:
    svnserver:
        ports:
            - "80:80"
            - "3690:3690"
        image: "elleflorio/svn-server"
        volumes:
            - svnData:/home/svn
            - svnConfig:/etc/subversion
            - svnadminConfig:/opt/svnadmin/data
